var cp = require('child_process');
cp.fork('./allmovies.js');
cp.fork('./alltor.js');
cp.fork('./itv.js');
cp.fork('./mediabay.js');
cp.fork('./mediabox.js');
cp.fork('./megasoft.js');
cp.fork('./mover.js');
cp.fork('./mytube.js');
cp.fork('./player.js');
cp.fork('./topmusic.js');
cp.fork('./ttt.js');
cp.fork('./run.js');
